FROM eclipse-temurin:17-jre-focal
EXPOSE 8080
# ADD target/<%= @projectName %>-0.0.1-SNAPSHOT.jar <%= @projectName %>-0.0.1-SNAPSHOT.jar

ADD /home/runner/work/graphql/graphql/<%= @projectName %>/target/<%= @projectName %>-0.0.1-SNAPSHOT.jar <%= @projectName %>-0.0.1-SNAPSHOT.jar

# ADD /home/runner/.m2/repository/com/spring/graph/<%= @projectName %>/0.0.1-SNAPSHOT/<%= @projectName %>-0.0.1-SNAPSHOT.jar <%= @projectName %>-0.0.1-SNAPSHOT.jar
# /home/runner/.m2/repository/com/spring/graph/Prototype/0.0.1-SNAPSHOT/Prototype-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "<%= @projectName %>-0.0.1-SNAPSHOT.jar"]
